version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: 123456
    volumes:
      - /path/to/other/postgresql/data:/var/lib/postgresql/data
