default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: weather
  password: '123456'
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: weather_db

test:
  <<: *default
  database: weather_db_test
